// <auto-generated />
using System;
using CovidApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CovidApi.Migrations
{
    [DbContext(typeof(CovidApiContext))]
    [Migration("20210126225452_SeedDbQuestionsUpdateProperties")]
    partial class SeedDbQuestionsUpdateProperties
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CovidApi.Models.Diagnosis", b =>
                {
                    b.Property<int>("DiagnosisId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Sex");

                    b.HasKey("DiagnosisId");

                    b.ToTable("Diagnoses");

                    b.HasData(
                        new
                        {
                            DiagnosisId = 1,
                            Age = 20,
                            Sex = "Female"
                        });
                });

            modelBuilder.Entity("CovidApi.Models.Evidence", b =>
                {
                    b.Property<int>("EvidenceId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AgeAnswer");

                    b.Property<bool?>("Cough");

                    b.Property<int?>("DiagnosisId");

                    b.Property<string>("Explanation");

                    b.Property<bool?>("Fever");

                    b.Property<string>("Question");

                    b.Property<string>("SexAnswer");

                    b.Property<bool?>("Sob");

                    b.Property<bool?>("YesNo");

                    b.HasKey("EvidenceId");

                    b.HasIndex("DiagnosisId");

                    b.ToTable("Evidences");

                    b.HasData(
                        new
                        {
                            EvidenceId = 1,
                            DiagnosisId = 1,
                            Question = "What is your sex?"
                        },
                        new
                        {
                            EvidenceId = 2,
                            DiagnosisId = 1,
                            Question = "What is your age?"
                        },
                        new
                        {
                            EvidenceId = 3,
                            DiagnosisId = 1,
                            Question = "Do you have an underlying conditions that put you at a high risk? List all that apply."
                        },
                        new
                        {
                            EvidenceId = 4,
                            DiagnosisId = 1,
                            Question = "Do you have any of the following symptoms?"
                        },
                        new
                        {
                            EvidenceId = 5,
                            DiagnosisId = 1,
                            Question = "Do you have any other symptoms? List all that apply"
                        },
                        new
                        {
                            EvidenceId = 6,
                            DiagnosisId = 1,
                            Question = "Have you recently lost the ability to smell or taste?"
                        },
                        new
                        {
                            EvidenceId = 7,
                            DiagnosisId = 1,
                            Question = "Please explain your current exposure level."
                        },
                        new
                        {
                            EvidenceId = 8,
                            DiagnosisId = 1,
                            Question = "Have you recently traveled?"
                        });
                });

            modelBuilder.Entity("CovidApi.Models.Evidence", b =>
                {
                    b.HasOne("CovidApi.Models.Diagnosis", "Diagnosis")
                        .WithMany("Evidences")
                        .HasForeignKey("DiagnosisId");
                });
#pragma warning restore 612, 618
        }
    }
}
