// <auto-generated />
using System;
using CovidApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CovidApi.Migrations
{
    [DbContext(typeof(CovidApiContext))]
    [Migration("20210126215137_CreateNullAnswersAddSecondQ")]
    partial class CreateNullAnswersAddSecondQ
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CovidApi.Models.Diagnosis", b =>
                {
                    b.Property<int>("DiagnosisId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Age");

                    b.Property<string>("Sex");

                    b.HasKey("DiagnosisId");

                    b.ToTable("Diagnoses");

                    b.HasData(
                        new
                        {
                            DiagnosisId = 1,
                            Age = 20,
                            Sex = "Female"
                        });
                });

            modelBuilder.Entity("CovidApi.Models.Evidence", b =>
                {
                    b.Property<int>("EvidenceId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AgeAnswer");

                    b.Property<int?>("DiagnosisId");

                    b.Property<string>("Explanation");

                    b.Property<bool?>("MultipleAnswer");

                    b.Property<string>("Question");

                    b.Property<string>("SexAnswer");

                    b.HasKey("EvidenceId");

                    b.HasIndex("DiagnosisId");

                    b.ToTable("Evidences");

                    b.HasData(
                        new
                        {
                            EvidenceId = 1,
                            DiagnosisId = 1,
                            Question = "What is your sex?",
                            SexAnswer = "Female"
                        },
                        new
                        {
                            EvidenceId = 2,
                            AgeAnswer = 20,
                            DiagnosisId = 1,
                            Question = "What is your age?"
                        });
                });

            modelBuilder.Entity("CovidApi.Models.Evidence", b =>
                {
                    b.HasOne("CovidApi.Models.Diagnosis", "Diagnosis")
                        .WithMany("Evidences")
                        .HasForeignKey("DiagnosisId");
                });
#pragma warning restore 612, 618
        }
    }
}
